### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by armin-reichert** [RussianManSMWC/Ms.-Pac-Man-NES-Tengen-Disassembly#1]
Dear RussianManSMWC,

would it be ok for you if we could get in contact per PM, as I have many questions on the Tengen Ms. Pac-Man game details. You can find my mail address on my GitHub home page.

As you probably know (many thanks for the 100th star!), I am currently integrating the Tengen Ms. Pac-Man game into my Java/JavaFX Pac-Man clones.

Thanks and best regards
Armin Reichert

**Comment by RussianManSMWC** [comment]
um, sure? Where do you want to get in contact? @armin-reichert

**Comment by armin-reichert** [comment]
Thanks for the quick answer. If you don't mind we could just use e-mail. Or is there some other medium you would prefer (forum, Discord etc.)?

**Comment by RussianManSMWC** [comment]
discord sounds convenient. my name is the same on there.

**Comment by armin-reichert** [comment]
Thanks, I will contact you there.
